title: From Tennessee to Chicago # You will insert your title here.
description: 

baseurl: "/TennesseeChicago_Transcriptions" # the subpath of your site. Change it if the name of your repository is other than "mindoc"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
